apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  # Các URI rút gọn (K8s sẽ tự động mã hóa dạng Base64 khi apply)
  user-db-uri: "mongodb+srv://voduytoan:Voduytoan7153@pcshop.91getcf.mongodb.net/user_db"
  product-db-uri: "mongodb+srv://voduytoan:Voduytoan7153@pcshop.91getcf.mongodb.net/product_db"
  order-db-uri: "mongodb+srv://voduytoan:Voduytoan7153@pcshop.91getcf.mongodb.net/order_db"
  payment-db-uri: "mongodb+srv://voduytoan:Voduytoan7153@pcshop.91getcf.mongodb.net/payment_db"
