import { useEffect, useState, useRef } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { Loader2, CheckCircle, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import axiosClient from "@/lib/axiosClient";

export default function PaymentResultPage() {
  document.title = "Kết quả thanh toán - PCShop";

  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [status, setStatus] = useState<"processing" | "success" | "failed">("processing");
  const [message, setMessage] = useState("Đang xử lý kết quả thanh toán...");
  const processed = useRef(false);

  useEffect(() => {
    // Only process once
    if (processed.current) return;
    processed.current = true;

    const processPaymentCallback = async () => {
      // Build JSON from URL search params generated by MoMo
      const callbackData: Record<string, string> = {};
      searchParams.forEach((value, key) => {
        callbackData[key] = value;
      });

      if (!callbackData.orderId) {
        setStatus("failed");
        setMessage("Dữ liệu thanh toán không hợp lệ.");
        return;
      }

      try {
        // Send to backend to verify signature and update order status
        // We use the same IPN endpoint because it accepts JSON map
        await axiosClient.post("/payments/callback/momo", callbackData);
        
        const isSuccess = callbackData.resultCode === "0";
        if (isSuccess) {
          navigate(`/order-success?id=${orderId}`, { replace: true });
        } else {
          navigate(`/order/${orderId}`, { replace: true });
        }
      } catch (err: any) {
        console.error("Payment verification failed:", err);
        const responseData = err?.response?.data;
        const errMsg = responseData?.message || "";
        
        const isSuccess = callbackData.resultCode === "0";
        if (isSuccess && (errMsg.includes("not in pending status") || err?.response?.status === 400 || err?.response?.status === 200)) {
           navigate(`/order-success?id=${orderId}`, { replace: true });
        } else if (isSuccess) {
           navigate(`/order-success?id=${orderId}`, { replace: true });
        } else {
           navigate(`/order/${orderId}`, { replace: true });
        }
      }
    };

    processPaymentCallback();
  }, [searchParams]);

  const rawOrderId = searchParams.get("orderId") || "";
  // Extract real orderId if it has the timestamp suffix
  const orderId = rawOrderId.includes("_") ? rawOrderId.split("_")[0] : rawOrderId;

  return (
    <div className="container mx-auto flex min-h-[60vh] items-center justify-center px-4 py-16">
      <div className="w-full max-w-md text-center rounded-lg border border-border bg-card p-8 shadow-sm">
        {status === "processing" && (
          <div className="flex flex-col items-center justify-center">
            <Loader2 className="h-16 w-16 animate-spin text-primary mb-4" />
            <h2 className="text-xl font-bold text-foreground">Đang xác thực...</h2>
            <p className="mt-2 text-muted-foreground">{message}</p>
          </div>
        )}

        {status === "success" && (
          <div className="flex flex-col items-center justify-center">
            <CheckCircle className="h-16 w-16 text-green-500 mb-4" />
            <h2 className="text-xl font-bold text-foreground">Giao dịch thành công</h2>
            <p className="mt-2 text-muted-foreground">{message}</p>
            <div className="mt-8 flex w-full flex-col gap-3">
              <Button onClick={() => navigate(`/order-success?id=${orderId}`)} className="w-full">
                Xem hóa đơn
              </Button>
            </div>
          </div>
        )}

        {status === "failed" && (
          <div className="flex flex-col items-center justify-center">
            <XCircle className="h-16 w-16 text-destructive mb-4" />
            <h2 className="text-xl font-bold text-foreground">Giao dịch thất bại</h2>
            <p className="mt-2 text-muted-foreground">{message}</p>
            <div className="mt-8 flex w-full flex-col gap-3">
              <Button onClick={() => navigate(`/order/${orderId}`)} variant="outline" className="w-full">
                Quay lại đơn hàng
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
